services:
  - type: web
    name: property-management-backend
    env: node
    plan: free
    buildCommand: cd src/backend && npm install && npm run build
    startCommand: cd src/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: property-management-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: property-management-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: "us-east-1"
      - key: AWS_S3_BUCKET
        sync: false
      - key: CORS_ORIGIN
        value: "https://property-management.vercel.app"

  - type: redis
    name: property-management-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

  - type: pserv
    name: property-management-db
    env: postgresql
    plan: free
    databaseName: property_management
    databaseUser: property_user
